Gadlix/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Web.urls',namespace="Web")),

    path('tinymce/', include('tinymce.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "GADLIX Administration"
admin.site.site_title = "GADLIX Admin Portal"
admin.site.index_title = "Welcome to GADLIX Admin Portal"

Web/urls.py
from django.urls import path

from . import views

app_name='Web'

urlpatterns = [
    path('', views.index,name='index'),
    path('about/', views.about,name='about'),
    path('services/', views.services,name='services'),
    path('service-details/<int:id>/', views.serviceDetails,name='serviceDetails'),
    path('gallery/', views.gallery,name='gallery'),
    path('updates/', views.blog,name='blog'),
    path('update-details/<str:slug>/', views.blogDetails,name='blogDetails'),
    path('contact/', views.contact,name='contact'),
    path('ajax/',views.ajax,name='ajax')


]

Web/models.py

from django.db import models
from versatileimagefield.fields import VersatileImageField,PPOIField
from tinymce.models import HTMLField


class Service(models.Model):
    title=models.CharField(max_length=225)
    summary=models.CharField(max_length=355)
    content = HTMLField(blank=True, null=True)
    image = VersatileImageField('Image',upload_to='services/',ppoi_field='ppoi')
    ppoi = PPOIField('Image PPOI')
    description=models.TextField()
    
    def __str__(self):
        return self.title


    
# class Term(models.Model):
#     service=models.ForeignKey(Service,on_delete=models.CASCADE)
#     term=HTMLField(blank=True,null=True)


class Gallery(models.Model):
    title=models.CharField(max_length=225)
    image = VersatileImageField('Image',upload_to='gallery/',ppoi_field='ppoi' )
    ppoi = PPOIField('Image PPOI')

    class Meta:
        verbose_name_plural = ("Gallery")

    def __str__(self):
        return str(self.title)



class Update(models.Model):
    title=models.CharField(max_length=225)
    summary=models.CharField(max_length=500)
    date=models.DateField()
    image=VersatileImageField('Image',upload_to='updates/',ppoi_field='ppoi' )
    ppoi = PPOIField('Image PPOI')
    content=HTMLField(blank=True, null=True)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return str(self.title)



class Client(models.Model):
    title=models.CharField(max_length=225)
    image=VersatileImageField('Image',upload_to='clients/',ppoi_field='ppoi' )
    ppoi = PPOIField('Image PPOI')

    def __str__(self):
        return str(self.title)


class Testimonial(models.Model):
    decription=models.CharField(max_length=500)
    name=models.CharField(max_length=225)
    designation=models.CharField(max_length=225)
    image=VersatileImageField('Image',upload_to='testimonials/',ppoi_field='ppoi' )
    ppoi = PPOIField('Image PPOI')

    def __str__(self):
        return str(self.name)



class Contact(models.Model):
    AD_CHOICES=(('outdoor_advertising','Outdoor Advertising'),('agent_partnership','Agent Partnership',))
    name=models.CharField(max_length=225)
    company=models.CharField(max_length=225)
    phone=models.CharField(max_length=12)
    email=models.EmailField()
    website=models.CharField(max_length=225)
    ad_type=models.CharField(max_length=128,choices=AD_CHOICES,default='Outdoor Advertising')

    def __str__(self):
        return str(self.name)








     

Web/forms.py

from django import forms

from .models import Contact
from django.forms.widgets import SelectMultiple, TextInput, Textarea, EmailInput, CheckboxInput,URLInput, Select, NumberInput, RadioSelect, FileInput


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields= '__all__'
        widgets={
            'name':TextInput(attrs={'class':'required form-control','placeholder':"Name"}),
            'company':TextInput(attrs={'class':'required form-control','placeholder':"Company"}),
            'phone':TextInput(attrs={'class':'required form-control','placeholder':"Phone"}),
            'email':EmailInput(attrs={'class':'form-control','placeholder':"Email"}),
            'website':TextInput(attrs={'class':'form-control','placeholder':"Website"}),
            
            'ad_type':RadioSelect(attrs={'id':"html", 'name':"fav" ,'value':"Outdoor_Advertising"}),
            # 'ad_type':RadioSelect(attrs={'id':"css", 'name':"fav" ,'value':"Agency_Partnership"}),


        }

Web/views.py

from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
from django.http import HttpResponse
from .models import Service, Gallery, Testimonial, Update,Client,Testimonial
from .forms import ContactForm
# Create your views here.
import json

def index(request):
    services = Service.objects.all()[:3]
    gallery1 = Gallery.objects.all().order_by('-id')[0:1]
    gallery2 = Gallery.objects.all().order_by('-id')[1:2]
    gallery3 = Gallery.objects.all().order_by('-id')[2:3]
    gallery4 = Gallery.objects.all().order_by('-id')[3:4]
    
    testimonial = Testimonial.objects.all()
    updates = Update.objects.all()
    forms=ContactForm(request.POST or None)

    context={
        "is_index" : True,
        "services":services,
        "gallery1":gallery1,
        "gallery2":gallery2,
        "gallery3":gallery3,
        "gallery4":gallery4,
       
        "testimonial":testimonial,
        'updates':updates,
        'forms':forms
    

    }
    return render(request,'web/index.html',context)


def about(request):
    testimonial = Testimonial.objects.all()
    context={
        "is_about" : True,
        'testimonial':testimonial

    }
    return render(request,'web/about.html',context)


def services(request):
    services = Service.objects.all()
    testimonial = Testimonial.objects.all()
    client = Client.objects.all()
    context={
        "is_service" : True,
        "services":services,
        "testimonial":testimonial,
        "client":client,

    }
    return render(request,'web/services.html',context)


def serviceDetails(request,id):
    service=Service.objects.get(id=id)
    # terms=Term.objects.filter(service=service)
    testimonial = Testimonial.objects.all()
    client = Client.objects.all()
    context={
        "service":service,
        # "terms":terms,
        "testimonial":testimonial,
        "client":client,
    }
    return render(request,'web/service-details.html',context)


def gallery(request):
    gallery = Gallery.objects.all()
    context={
        "is_gallery" : True,
        "gallery":gallery

    }
    return render(request,'web/gallery.html',context)


def blog(request):
    updates=Update.objects.all()
    context={
        "is_updates" : True,
        "updates":updates,

    }
    return render(request,'web/blog.html',context)


def blogDetails(request,slug):
    update = get_object_or_404(Update,slug=slug)
    updates=Update.objects.exclude(pk=update.pk)[:3]
    context={
        'update':update,
        'updates':updates
    }
    return render(request,'web/blog-details.html',context)


def contact(request):
    forms=ContactForm(request.POST or None)
    context={
        'forms':forms

    }
    return render(request,'web/contact.html',context)

def ajax(request):
    forms=ContactForm(request.POST or None)
    if request.method=='POST':
        if forms.is_valid():
            forms.save()
            response_data = {
                "status":"true",
                "title":"Successfully Submitted",
                "message":"Messages successfully updated"
            }
        return JsonResponse({'title':response_data})

templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gadlix</title>
    <!-- favicon -->
    <link rel=icon href="{% static 'web/img/GADLIX ICON.png' %}" sizes="20x20" type="image/png">
    <!-- animate -->
    <link rel="stylesheet" href="{% static 'web/css/animate.css' %}">
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">
    <!-- magnific popup -->
    <link rel="stylesheet" href="{% static 'web/css/magnific-popup.css' %}">
    <!-- owl carousel -->
    <link rel="stylesheet" href="{% static 'web/css/owl.carousel.min.css' %}">
    <!-- fontawesome -->
    <link rel="stylesheet" href="{% static 'web/css/font-awesome.min.css' %}">
    <!-- flaticon -->
    <link rel="stylesheet" href="{% static 'web/css/flaticon.css' %}">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <!-- responsive Stylesheet -->
    <link rel="stylesheet" href="{% static 'web/css/responsive.css' %}">

</head>

<body>
    <div class="body-overlay" id="body-overlay"></div>
    {% include 'web/partials/header.html'  %}
    {% block content %}
    
    {% endblock %}
    {% include 'web/partials/footer.html'  %}


   <!-- preloader area start -->
   <div id="preloader">
       <div id="loader"></div>
    </div>
    <!-- preloader area end -->
    
    <!-- jquery -->
    <script src="{% static 'web/js/jquery-2.2.4.min.js' %}"></script>
<!-- popper -->
<script src="{% static 'web/js/popper.min.js' %}"></script>
<!-- bootstrap -->
<script src="{% static 'web/js/bootstrap.min.js' %}"></script>
<!-- magnific popup -->
<script src="{% static 'web/js/jquery.magnific-popup.js' %}"></script>
<!-- wow -->
<script src="{% static 'web/js/wow.min.js' %}"></script>
<!-- owl carousel -->
<script src="{% static 'web/js/owl.carousel.min.js' %}"></script>
<!-- waypoint -->
<script src="{% static 'web/js/waypoints.min.js' %}"></script>
<!-- counterup -->
<script src="{% static 'web/js/jquery.counterup.min.js' %}"></script>
<!-- imageloaded -->
<script src="{% static 'web/js/imagesloaded.pkgd.min.js' %}"></script>
<!-- isotope -->
<script src="{% static 'web/js/isotope.pkgd.min.js' %}"></script>
<!-- Progress-Bar -->
<script src="{% static 'web/js/jQuery.rProgressbar.min.js' %}"></script>
<!-- Progress-Bar Active js -->
<script src="{% static 'web/js/active.rProgressbar.js' %}"></script>



<!-- main js -->
<script src="{% static 'web/js/main.js' %}"></script>



</body>

</html>

templates/web/contact.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb Area -->
    <div class="breadcrumb-area  margin-bottom-120" style="background-image:url({% static 'web/img/breadcrumb/01.jpg' %});">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb-inner">
                        <span>Contact Us</span>
                        <h2 class="page-title">Keep in touch with us with anytime</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Area -->
    <div class="contact-inner-area padding-bottom-80">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="contact-inner-content margin-bottom-20">
                        <h2 class="title-md">
                            Let's discuss your new projects now
                        </h2>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="single-contact-item margin-bottom-40">
                                <h3 class="title">Address</h3>
                                <p>MA Arcade, Near Calicut Airport, Kerala, India</p>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="single-contact-item margin-bottom-40">
                                <h3 class="title">Call Us</h3>
                                <a href="tel:+91 96053 64611">+91 96053 64611</a>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="single-contact-item margin-bottom-40">
                                <h3 class="title">office time</h3>
                                <p>Wednesday – Saturday <br> 6 am to 8 pm EST</p>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="single-contact-item margin-bottom-40">
                                <h3 class="title">Mail Us</h3>
                                <a href="mailto:info@gadlix.com">info@gadlix.com</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="col-lg-6">
                    <div class="contact-form">
                        <form action="" class="contact-page-form" method="POST" novalidate="novalidate" id="form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        {{forms.name}}                                   
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        {{forms.company}}
                                        <!-- <input type="text" name="lname" placeholder="Company" class="form-control" required="" aria-required="true"> -->
                                    </div>
                                </div>
                                
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        {{forms.phone}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        {{forms.email}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        {{forms.website}}
                                    </div>
                                <div>
                                    <h6>Let us know what you're interested in! Check all that apply</h6>
                                    <span>Area of Interest </span><br>
                                    {{forms.ad_type}}
                                </div>

                                </div>
                                <div class="col-md-12" style="padding-top: 15px;">
                                    <div class="form-group btn-wrapper">
                                        <input type="submit" value="Submit Message" class="boxed-btn" style="border: none;">
                                    </div>
                                </div>

                        
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Map Area -->
    <div class="map-area">
        <div class="container-fluid p-0">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="contact_map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3914.487589643727!2d75.9481966141193!3d11.151488855209529!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xff85f70cdb53a39a!2zMTHCsDA5JzA1LjMiTiA3NcKwNTcnMDEuNCJF!5e0!3m2!1sen!2sin!4v1643793767106!5m2!1sen!2sin" style="border:0;width: 100%;height: 450px;" allowfullscreen="" loading="lazy"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    {% endblock %}

templates/web/partials/clients.html
<div class="client-area">
    <div class="client-active-area">


        {% for client in clients %}
        <div class="single-brand">
            <a href="#"><img src="{{client.image.crop.151x41}}" alt=""></a>
        </div>
        {% endfor %}



    </div>
</div>

templates/web/partials/footer.html
{% load static %}
<div class="contact-area padding-top-120 padding-bottom-120">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="section-title white">
                    <h2 class="title">want to work with us ?</h2>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="contact-content">
                    <h4 class="title">
                        Contact us
                    </h4>
                    <p>MA Arcade, Near Calicut Airport, Kerala, India
                        info@gadlix.com <br>
                        +91 96053 64611</p>
                </div>
            </div>
        </div>
    </div>
</div>
  <!-- footer area start -->
  <footer class="footer-area">
    <div class="footer-top padding-top-115 padding-bottom-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget widget">
                        <div class="about_us_widget">
                            <a href="index.html" class="footer-logo"> <img src="{% static 'web/img/GADLIX-WHITE.png' %}" alt="footer logo"></a>
                            <p>© Copyrights 2022 Gadlix.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget widget widget_nav_menu">
                        <h4 class="widget-title">Quick links</h4>
                        <ul>
                            <li><a href="{% url 'Web:index' %}">Home</a></li>
                            <li><a href="{% url 'Web:about' %}">About</a></li>
                            <li><a href="{% url 'Web:services' %}">Services</a></li>
                            <li><a href="{% url 'Web:gallery' %}">Gallery</a></li>
                            <li><a href="{% url 'Web:blog' %}">Updates</a></li>
                            <li><a href="{% url 'Web:contact' %}">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget widget widget_nav_menu">
                        <h4 class="widget-title">Quick links</h4>
                        <ul>
                            <li><a href="/#home">Home</a></li>
                            <li><a href="/#about">About</a></li>
                            <li><a href="/#service">Services</a></li>
                            <li><a href="/#gallery">Gallery</a></li>
                            <li><a href="/#updates">Updates</a></li>
                            <li><a href="/#contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget widget ">
                        <h4 class="widget-title">Subscribe </h4>
                        <div class="subscribe-area">
                            <form class="subscribe-form" action="https://freakytheme.com/html/outmedia/index.html">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Email" />
                                    <div class="icon"><i class="far fa-envelope"></i></div>
                                </div>
                                <button type="submit" class="subscribe-btn"><i class="flaticon-send"></i></button>
                            </form>
                        </div>
                        <div>
                            <ul class="social_share">
                                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer area end -->



<!-- back to top area start -->
<div class="back-to-top">
    <span class="back-top"><i class="fa fa-angle-up"></i></span>
</div>
<!-- back to top area end -->

templates/web/partials/header.html
 {% load static %}
    <div class="header">
        <!-- support bar area end -->
        <nav class="navbar nav-custom navbar-expand-lg">
            <div class="container nav-custom-container">
                <div class="responsive-mobile-menu">
                    <div class="logo-wrapper">
                        <a href="{% url 'Web:index' %}" class="logo">
    
                            <img class="def" src="{% static 'web/img/GADLIX-WHITE.png' %}" alt="">
                            <img class="alt" src="{% static 'web/img/GADLIX-BLACK.png' %}" alt="">
                        </a>
                    </div>
                    <button class="navbar-toggler cross-menu" type="button" data-toggle="collapse" data-target="#bizcoxx_main_menu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="cross-menu-wrapper">
                            <span class="bar1"></span>
                            <span class="bar2"></span>
                            <span class="bar3"></span>
                        </span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bizcoxx_main_menu">
                    <ul class="nav-custom-menu navbar-nav">
                        <li class="{% if is_index %}current-menu-item{% endif %}">
                            <a href="{% url 'Web:index' %}">Home</a>
                        </li>
                        <li class="{% if is_about %}current-menu-item{% endif %}">
                            <a href="{% url 'Web:about' %}">About</a>
                            <!--<ul class="sub-menu">
            <li><a href="about.html">About</a></li>
            <li><a href="service-details.html">Service Single</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>-->
                        </li>
                        <li class="{% if is_service %}current-menu-item{% endif %}" >
                            <a href="{% url 'Web:services' %}">Services</a>
                        </li>
                        <li class="{% if is_gallery %}current-menu-item{% endif %}"><a href="{% url 'Web:gallery' %}">Gallery</a></li>
                        <li class="{% if is_update %}current-menu-item{% endif %}"><a href="{% url 'Web:blog' %}">Updates</a></li>
                        <!--<li><a href="blog-details.html">Blog</a></li>-->
                    </ul>
                </div>
                <div class="nav-right-content">
                    <div class="icon-part">
                        <ul class="social_link">
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                        </ul>
                        <!-- <ul class="cart-icon">
                            <li id="search"><a href="#"><i class="flaticon-magnifying-glass
                                                    "></i></a></li>
                            <li class="cart"><a href="#"><i class="flaticon-shopping-bag"></i></a></li>
                        </ul> -->
                    </div>
                    <div class="btn-wrapper">
                        <a href="{% url 'Web:contact' %}" class="boxed-btn blank">contact us</a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- navbar area end -->
    </div>